name: Docker Release
on:
  push:
    tags: [ 'v*' ]

jobs:
  deploy:
    name: Deploy to Docker add-on with tag
    runs-on: ubuntu-latest
    environment: CI - release environment
    strategy:
      matrix:
        nomad-version: ["1.5.13", "1.6.6", "1.7.2"]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          version_format: "${major}.${minor}.${patch}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🛠️ Run Buildx
        working-directory: src/Nomad.NodeTermHandler
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --file ./Dockerfile . \
            --build-arg NOMADVERSION=${{ matrix.nomad-version }} \
            --compress \
            --tag "awsex/nomad-node-term-handler:${{ steps.version.outputs.version }}-nomad${{ matrix.nomad-version }}" \
            --tag "awsex/nomad-node-term-handler:latest-nomad${{ matrix.nomad-version }}" \
            --tag "awsex/nomad-node-term-handler:latest"
